### ISSUE TITLE
Scout roles gets written to scoutd.yml as single string; needs to be an array:

### ISSUE THREAD

**Issue by heyryanw** [pingdomserver/scout_cookbooks#41]
https://github.com/scoutapp/scout_cookbooks/blob/fba1410dd1f0e6fe35ae336baaf716e0a5b6c1d6/recipes/default.rb#L88

Assigning variables in this way will leave the result as a single string. This value needs to be an array, since nodes in chef, and in scout itself, can belong to multiple roles. Can maybe push a PR later, but wanted to report now.

For background: we assign node/scout roles from Chef Roles pulled from a chef server. The node[:roles] array is as we expect it to be, but the scout_cookbook run is what sets the value for the scoutd.yml, and reports back to the scout service, resulting in every node on belonging to one role in Scout.

**Comment by skiold** [comment]
@heyryanw the cookbook changed the format of node['scout']['roles'] when scoutapp moved to the new agent.

The recipe expects you to build the actual roles string found in `/etc/scout/scoutd.yml`, ie comma separated role names :(

**Comment by heyryanw** [comment]
Well that's unfortunate. This won't work out very well in Chef-land since the basics of the cookbook (in practice and documentation) suggest you should attach Scout roles to nodes via Chef roles, and if you have a node which belongs to multiple roles, only one of the roles will exist in scoutd.yml after a Chef run. 

Any suggestions on getting around this?

**Comment by kylev** [comment]
```ruby
:roles => node[:scout][:roles].respond_to?(:join) ? node[:scout][:roles].join(',') : node[:scout][:roles]
```
