### ISSUE TITLE
Please bump version

### ISSUE THREAD

**Issue by Drewzar** [pingdomserver/scout_cookbooks#52]
Please bump the version of this cookbook in the `metadata.rb` since https://github.com/pingdomserver/scout_cookbooks/pull/51 was merged.

**Comment by sleepingstu** [comment]
Currently getting this error when using version 0.4.6:

_remote_file[/var/chef/cache/https___archive_scoutapp_com_scout-archive_key] (/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/provider/apt_repository.rb line 162) had an error: OpenSSL::SSL::SSLError: SSL Error connecting to https://archive.scoutapp.com/scout-archive.key - SSL_connect returned=1 errno=0 state=error: certificate verify failed_

**Comment by sleepingstu** [comment]
@okapusta do you know when this will be pushed to the supermarket? Is still 0.4.6 on there.

https://supermarket.chef.io/cookbooks?utf8=%E2%9C%93&q=scout

**Comment by barlima** [comment]
@sleepingstu @Drewzar The version has been bumped
